### ISSUE TITLE
Build error with snappy on Ubuntu

### ISSUE THREAD

**Issue by stloyd** [crazywhalecc/static-php-cli#195]
When trying to build the binary with micro + snappy on Ubuntu it fails (while on OSX it works well):

Error log:
```
/bin/bash /home/runner/work/flow/flow/source/php-src/libtool --silent --preserve-dup-deps --tag CC --mode=compile musl-gcc -Isapi/micro/ -I/home/runner/work/flow/flow/source/php-src/sapi/micro/ -I/home/runner/work/flow/flow/source/php-src/include -I/home/runner/work/flow/flow/source/php-src/main -I/home/runner/work/flow/flow/source/php-src -I/home/runner/work/flow/flow/source/php-src/ext/date/lib -I/home/runner/work/flow/flow/buildroot/lib/pkgconfig/../../include/libxml2 -I/home/runner/work/flow/flow/buildroot/include -I/home/runner/work/flow/flow/source/php-src/ext/mbstring/libmbfl -I/home/runner/work/flow/flow/source/php-src/ext/mbstring/libmbfl/mbfl -I/home/runner/work/flow/flow/source/php-src/TSRM -I/home/runner/work/flow/flow/source/php-src/Zend    -fno-common -Wstrict-prototypes -Wformat-truncation -Wlogical-op -Wduplicated-cond -Wno-clobbered -Wall -Wextra -Wno-strict-aliasing -Wno-unused-parameter -Wno-sign-compare -fvisibility=hidden -Wimplicit-fallthrough=1 -DZEND_SIGNALS  -g -Os -fno-ident -Xcompiler -march=corei7 -Xcompiler -mtune=core-avx2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1  -c /home/runner/work/flow/flow/source/php-src/sapi/micro/php_micro_hooks.c -o sapi/micro/php_micro_hooks.lo  -MMD -MF sapi/micro/php_micro_hooks.dep -MT sapi/micro/php_micro_hooks.lo
/bin/bash /home/runner/work/flow/flow/source/php-src/libtool --silent --preserve-dup-deps --tag CC --mode=compile musl-gcc -Isapi/cli/ -I/home/runner/work/flow/flow/source/php-src/sapi/cli/ -I/home/runner/work/flow/flow/source/php-src/include -I/home/runner/work/flow/flow/source/php-src/main -I/home/runner/work/flow/flow/source/php-src -I/home/runner/work/flow/flow/source/php-src/ext/date/lib -I/home/runner/work/flow/flow/buildroot/lib/pkgconfig/../../include/libxml2 -I/home/runner/work/flow/flow/buildroot/include -I/home/runner/work/flow/flow/source/php-src/ext/mbstring/libmbfl -I/home/runner/work/flow/flow/source/php-src/ext/mbstring/libmbfl/mbfl -I/home/runner/work/flow/flow/source/php-src/TSRM -I/home/runner/work/flow/flow/source/php-src/Zend    -fno-common -Wstrict-prototypes -Wformat-truncation -Wlogical-op -Wduplicated-cond -Wno-clobbered -Wall -Wextra -Wno-strict-aliasing -Wno-unused-parameter -Wno-sign-compare -fvisibility=hidden -Wimplicit-fallthrough=1 -DZEND_SIGNALS  -g -Os -fno-ident -Xcompiler -march=corei7 -Xcompiler -mtune=core-avx2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /home/runner/work/flow/flow/source/php-src/sapi/cli/php_cli_process_title.c -o sapi/cli/php_cli_process_title.lo  -MMD -MF sapi/cli/php_cli_process_title.dep -MT sapi/cli/php_cli_process_title.lo
/bin/bash /home/runner/work/flow/flow/source/php-src/libtool --silent --preserve-dup-deps --tag CC --mode=compile musl-gcc -Isapi/cli/ -I/home/runner/work/flow/flow/source/php-src/sapi/cli/ -I/home/runner/work/flow/flow/source/php-src/include -I/home/runner/work/flow/flow/source/php-src/main -I/home/runner/work/flow/flow/source/php-src -I/home/runner/work/flow/flow/source/php-src/ext/date/lib -I/home/runner/work/flow/flow/buildroot/lib/pkgconfig/../../include/libxml2 -I/home/runner/work/flow/flow/buildroot/include -I/home/runner/work/flow/flow/source/php-src/ext/mbstring/libmbfl -I/home/runner/work/flow/flow/source/php-src/ext/mbstring/libmbfl/mbfl -I/home/runner/work/flow/flow/source/php-src/TSRM -I/home/runner/work/flow/flow/source/php-src/Zend    -fno-common -Wstrict-prototypes -Wformat-truncation -Wlogical-op -Wduplicated-cond -Wno-clobbered -Wall -Wextra -Wno-strict-aliasing -Wno-unused-parameter -Wno-sign-compare -fvisibility=hidden -Wimplicit-fallthrough=1 -DZEND_SIGNALS  -g -Os -fno-ident -Xcompiler -march=corei7 -Xcompiler -mtune=core-avx2 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -c /home/runner/work/flow/flow/source/php-src/sapi/cli/ps_title.c -o sapi/cli/ps_title.lo  -MMD -MF sapi/cli/ps_title.dep -MT sapi/cli/ps_title.lo
make micro_2s_objs SFX_FILESIZE=0xcafebabe
make[1]: Entering directory '/home/runner/work/flow/flow/source/php-src'
rm sapi/micro/php_micro_fileinfo.lo || :
rm: cannot remove 'sapi/micro/php_micro_fileinfo.lo': No such file or directory
make sapi/micro/php_micro_fileinfo.lo
make[2]: Entering directory '/home/runner/work/flow/flow/source/php-src'
/bin/bash /home/runner/work/flow/flow/source/php-src/libtool --silent --preserve-dup-deps --tag CC --mode=compile musl-gcc -Isapi/micro/ -I/home/runner/work/flow/flow/source/php-src/sapi/micro/ -I/home/runner/work/flow/flow/source/php-src/include -I/home/runner/work/flow/flow/source/php-src/main -I/home/runner/work/flow/flow/source/php-src -I/home/runner/work/flow/flow/source/php-src/ext/date/lib -I/home/runner/work/flow/flow/buildroot/lib/pkgconfig/../../include/libxml2 -I/home/runner/work/flow/flow/buildroot/include -I/home/runner/work/flow/flow/source/php-src/ext/mbstring/libmbfl -I/home/runner/work/flow/flow/source/php-src/ext/mbstring/libmbfl/mbfl -I/home/runner/work/flow/flow/source/php-src/TSRM -I/home/runner/work/flow/flow/source/php-src/Zend    -fno-common -Wstrict-prototypes -Wformat-truncation -Wlogical-op -Wduplicated-cond -Wno-clobbered -Wall -Wextra -Wno-strict-aliasing -Wno-unused-parameter -Wno-sign-compare -fvisibility=hidden -Wimplicit-fallthrough=1 -DZEND_SIGNALS  -g -Os -fno-ident -Xcompiler -march=corei7 -Xcompiler -mtune=core-avx2 -DSFX_FILESIZE=0xcafebabe -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1  -c /home/runner/work/flow/flow/source/php-src/sapi/micro/php_micro_fileinfo.c -o sapi/micro/php_micro_fileinfo.lo  -MMD -MF sapi/micro/php_micro_fileinfo.dep -MT sapi/micro/php_micro_fileinfo.lo
make[2]: Leaving directory '/home/runner/work/flow/flow/source/php-src'
make[1]: Leaving directory '/home/runner/work/flow/flow/source/php-src'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(guard.o): in function `__cxa_guard_acquire':
(.text.__cxa_guard_acquire+0x17): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(guard.o): in function `__cxa_guard_abort':
(.text.__cxa_guard_abort+0x7): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(guard.o): in function `__cxa_guard_release':
(.text.__cxa_guard_release+0x7): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(stdexcept.o): in function `std::logic_error::~logic_error()':
(.text._ZNSt11logic_errorD2Ev+0x63): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(stdexcept.o): in function `std::runtime_error::~runtime_error()':
(.text._ZNSt13runtime_errorD2Ev+0x63): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(stdexcept.o):(.text._ZNSt11logic_errorC2ERKSs+0x73): more undefined references to `__libc_single_threaded' follow
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(cp-demangle.o): in function `d_append_num':
(.text+0x8d8): undefined reference to `__sprintf_chk'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(cp-demangle.o): in function `d_print_comp_inner':
(.text+0x5226): undefined reference to `__sprintf_chk'
/usr/bin/ld: (.text+0x61d4): undefined reference to `__sprintf_chk'
/usr/bin/ld: (.text+0x62e3): undefined reference to `__sprintf_chk'
/usr/bin/ld: (.text+0x68ec): undefined reference to `__sprintf_chk'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(cp-demangle.o):(.text+0x69be): more undefined references to `__sprintf_chk' follow
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(cow-string-inst.o): in function `std::string::_Rep::_M_dispose(std::allocator<char> const&)':
(.text._ZNSs4_Rep10_M_disposeERKSaIcE[_ZNSs4_Rep10_M_disposeERKSaIcE]+0x13): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(cow-string-inst.o): in function `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()':
(.text._ZNSsD2Ev[_ZNSsD5Ev]+0x43): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(cow-string-inst.o): in function `std::string::clear()':
(.text._ZNSs5clearEv[_ZNSs5clearEv]+0x8b): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(cow-string-inst.o): in function `std::string::_M_mutate(unsigned long, unsigned long, unsigned long)':
(.text._ZNSs9_M_mutateEmmm[_ZNSs9_M_mutateEmmm]+0x1cb): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(cow-string-inst.o): in function `std::string::_Rep::_M_refcopy()':
(.text._ZNSs4_Rep10_M_refcopyEv[_ZNSs4_Rep10_M_refcopyEv]+0x1b): undefined reference to `__libc_single_threaded'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/./libstdc++.a(cow-string-inst.o):(.text._ZNSs7reserveEm[_ZNSs7reserveEm]+0x83): more undefined references to `__libc_single_threaded' follow
collect2: error: ld returned 1 exit status
make: *** [Makefile:279: sapi/micro/micro.sfx] Error 1
/bin/bash /home/runner/work/flow/flow/source/php-src/libtool --silent --preserve-dup-deps --tag CC --mode=link musl-gcc -export-dynamic -fno-common -Wstrict-prototypes -Wformat-truncation -Wlogical-op -Wduplicated-cond -Wno-clobbered -Wall -Wextra -Wno-strict-aliasing -Wno-unused-parameter -Wno-sign-compare -fvisibility=hidden -Wimplicit-fallthrough=1 -DZEND_SIGNALS  -g -Os -fno-ident -Xcompiler -march=corei7 -Xcompiler -mtune=core-avx2 -all-static  -R /home/runner/work/flow/flow/buildroot/lib/pkgconfig/../../lib -R /home/runner/work/flow/flow/buildroot/lib ext/date/php_date.lo ext/date/lib/astro.lo ext/date/lib/dow.lo ext/date/lib/parse_date.lo ext/date/lib/parse_tz.lo ext/date/lib/parse_posix.lo ext/date/lib/timelib.lo ext/date/lib/tm2unixtime.lo ext/date/lib/unixtime2tm.lo ext/date/lib/parse_iso_intervals.lo ext/date/lib/interval.lo ext/libxml/libxml.lo ext/openssl/openssl.lo ext/openssl/xp_ssl.lo ext/pcre/pcre2lib/pcre2_auto_possess.lo ext/pcre/pcre2lib/pcre2_chartables.lo ext/pcre/pcre2lib/pcre2_compile.lo ext/pcre/pcre2lib/pcre2_config.lo ext/pcre/pcre2lib/pcre2_context.lo ext/pcre/pcre2lib/pcre2_dfa_match.lo ext/pcre/pcre2lib/pcre2_error.lo ext/pcre/pcre2lib/pcre2_jit_compile.lo ext/pcre/pcre2lib/pcre2_maketables.lo ext/pcre/pcre2lib/pcre2_match.lo ext/pcre/pcre2lib/pcre2_match_data.lo ext/pcre/pcre2lib/pcre2_newline.lo ext/pcre/pcre2lib/pcre2_ord2utf.lo ext/pcre/pcre2lib/pcre2_pattern_info.lo ext/pcre/pcre2lib/pcre2_serialize.lo ext/pcre/pcre2lib/pcre2_string_utils.lo ext/pcre/pcre2lib/pcre2_study.lo ext/pcre/pcre2lib/pcre2_substitute.lo ext/pcre/pcre2lib/pcre2_substring.lo ext/pcre/pcre2lib/pcre2_tables.lo ext/pcre/pcre2lib/pcre2_ucd.lo ext/pcre/pcre2lib/pcre2_valid_utf.lo ext/pcre/pcre2lib/pcre2_xclass.lo ext/pcre/pcre2lib/pcre2_find_bracket.lo ext/pcre/pcre2lib/pcre2_convert.lo ext/pcre/pcre2lib/pcre2_extuni.lo ext/pcre/pcre2lib/pcre2_script_run.lo ext/pcre/php_pcre.lo ext/zlib/zlib.lo ext/zlib/zlib_fopen_wrapper.lo ext/zlib/zlib_filter.lo ext/bcmath/bcmath.lo ext/bcmath/libbcmath/src/add.lo ext/bcmath/libbcmath/src/div.lo ext/bcmath/libbcmath/src/init.lo ext/bcmath/libbcmath/src/neg.lo ext/bcmath/libbcmath/src/raisemod.lo ext/bcmath/libbcmath/src/sub.lo ext/bcmath/libbcmath/src/compare.lo ext/bcmath/libbcmath/src/divmod.lo ext/bcmath/libbcmath/src/int2num.lo ext/bcmath/libbcmath/src/num2long.lo ext/bcmath/libbcmath/src/output.lo ext/bcmath/libbcmath/src/recmul.lo ext/bcmath/libbcmath/src/sqrt.lo ext/bcmath/libbcmath/src/zero.lo ext/bcmath/libbcmath/src/debug.lo ext/bcmath/libbcmath/src/doaddsub.lo ext/bcmath/libbcmath/src/nearzero.lo ext/bcmath/libbcmath/src/num2str.lo ext/bcmath/libbcmath/src/raise.lo ext/bcmath/libbcmath/src/rmzero.lo ext/bcmath/libbcmath/src/str2num.lo ext/dom/php_dom.lo ext/dom/attr.lo ext/dom/document.lo ext/dom/domexception.lo ext/dom/parentnode.lo ext/dom/processinginstruction.lo ext/dom/cdatasection.lo ext/dom/documentfragment.lo ext/dom/domimplementation.lo ext/dom/element.lo ext/dom/node.lo ext/dom/characterdata.lo ext/dom/documenttype.lo ext/dom/entity.lo ext/dom/nodelist.lo ext/dom/text.lo ext/dom/comment.lo ext/dom/entityreference.lo ext/dom/notation.lo ext/dom/xpath.lo ext/dom/dom_iterators.lo ext/dom/namednodemap.lo ext/fileinfo/fileinfo.lo ext/fileinfo/libmagic/apprentice.lo ext/fileinfo/libmagic/apptype.lo ext/fileinfo/libmagic/ascmagic.lo ext/fileinfo/libmagic/cdf.lo ext/fileinfo/libmagic/cdf_time.lo ext/fileinfo/libmagic/compress.lo ext/fileinfo/libmagic/encoding.lo ext/fileinfo/libmagic/fsmagic.lo ext/fileinfo/libmagic/funcs.lo ext/fileinfo/libmagic/is_json.lo ext/fileinfo/libmagic/is_tar.lo ext/fileinfo/libmagic/magic.lo ext/fileinfo/libmagic/print.lo ext/fileinfo/libmagic/readcdf.lo ext/fileinfo/libmagic/softmagic.lo ext/fileinfo/libmagic/der.lo ext/fileinfo/libmagic/buffer.lo ext/fileinfo/libmagic/is_csv.lo ext/filter/filter.lo ext/filter/sanitizing_filters.lo ext/filter/logical_filters.lo ext/filter/callback_filter.lo ext/gmp/gmp.lo ext/hash/hash.lo ext/hash/hash_md.lo ext/hash/hash_sha.lo ext/hash/hash_ripemd.lo ext/hash/hash_haval.lo ext/hash/hash_tiger.lo ext/hash/hash_gost.lo ext/hash/hash_snefru.lo ext/hash/hash_whirlpool.lo ext/hash/hash_adler32.lo ext/hash/hash_crc32.lo ext/hash/hash_fnv.lo ext/hash/hash_joaat.lo ext/hash/sha3/generic64lc/KeccakP-1600-opt64.lo ext/hash/sha3/generic64lc/KeccakHash.lo ext/hash/sha3/generic64lc/KeccakSponge.lo ext/hash/hash_sha3.lo ext/hash/murmur/PMurHash.lo ext/hash/murmur/PMurHash128.lo ext/hash/hash_murmur.lo ext/hash/hash_xxhash.lo ext/json/json.lo ext/json/json_encoder.lo ext/json/json_parser.lo ext/json/json_scanner.lo ext/mbstring/mbstring.lo ext/mbstring/php_unicode.lo ext/mbstring/mb_gpc.lo ext/mbstring/libmbfl/filters/html_entities.lo ext/mbstring/libmbfl/filters/mbfilter_7bit.lo ext/mbstring/libmbfl/filters/mbfilter_base64.lo ext/mbstring/libmbfl/filters/mbfilter_big5.lo ext/mbstring/libmbfl/filters/mbfilter_cp5022x.lo ext/mbstring/libmbfl/filters/mbfilter_cp51932.lo ext/mbstring/libmbfl/filters/mbfilter_cp932.lo ext/mbstring/libmbfl/filters/mbfilter_cp936.lo ext/mbstring/libmbfl/filters/mbfilter_gb18030.lo ext/mbstring/libmbfl/filters/mbfilter_euc_cn.lo ext/mbstring/libmbfl/filters/mbfilter_euc_jp.lo ext/mbstring/libmbfl/filters/mbfilter_euc_jp_2004.lo ext/mbstring/libmbfl/filters/mbfilter_euc_jp_win.lo ext/mbstring/libmbfl/filters/mbfilter_euc_kr.lo ext/mbstring/libmbfl/filters/mbfilter_euc_tw.lo ext/mbstring/libmbfl/filters/mbfilter_htmlent.lo ext/mbstring/libmbfl/filters/mbfilter_hz.lo ext/mbstring/libmbfl/filters/mbfilter_iso2022_jp_ms.lo ext/mbstring/libmbfl/filters/mbfilter_iso2022jp_2004.lo ext/mbstring/libmbfl/filters/mbfilter_iso2022jp_mobile.lo ext/mbstring/libmbfl/filters/mbfilter_iso2022_kr.lo ext/mbstring/libmbfl/filters/mbfilter_jis.lo ext/mbstring/libmbfl/filters/mbfilter_qprint.lo ext/mbstring/libmbfl/filters/mbfilter_singlebyte.lo ext/mbstring/libmbfl/filters/mbfilter_sjis.lo ext/mbstring/libmbfl/filters/mbfilter_sjis_mobile.lo ext/mbstring/libmbfl/filters/mbfilter_sjis_mac.lo ext/mbstring/libmbfl/filters/mbfilter_sjis_2004.lo ext/mbstring/libmbfl/filters/mbfilter_tl_jisx0201_jisx0208.lo ext/mbstring/libmbfl/filters/mbfilter_ucs2.lo ext/mbstring/libmbfl/filters/mbfilter_ucs4.lo ext/mbstring/libmbfl/filters/mbfilter_uhc.lo ext/mbstring/libmbfl/filters/mbfilter_utf16.lo ext/mbstring/libmbfl/filters/mbfilter_utf32.lo ext/mbstring/libmbfl/filters/mbfilter_utf7.lo ext/mbstring/libmbfl/filters/mbfilter_utf7imap.lo ext/mbstring/libmbfl/filters/mbfilter_utf8.lo ext/mbstring/libmbfl/filters/mbfilter_utf8_mobile.lo ext/mbstring/libmbfl/filters/mbfilter_uuencode.lo ext/mbstring/libmbfl/mbfl/mbfilter.lo ext/mbstring/libmbfl/mbfl/mbfilter_8bit.lo ext/mbstring/libmbfl/mbfl/mbfilter_pass.lo ext/mbstring/libmbfl/mbfl/mbfilter_wchar.lo ext/mbstring/libmbfl/mbfl/mbfl_convert.lo ext/mbstring/libmbfl/mbfl/mbfl_encoding.lo ext/mbstring/libmbfl/mbfl/mbfl_filter_output.lo ext/mbstring/libmbfl/mbfl/mbfl_language.lo ext/mbstring/libmbfl/mbfl/mbfl_memory_device.lo ext/mbstring/libmbfl/mbfl/mbfl_string.lo ext/mbstring/libmbfl/nls/nls_de.lo ext/mbstring/libmbfl/nls/nls_en.lo ext/mbstring/libmbfl/nls/nls_ja.lo ext/mbstring/libmbfl/nls/nls_kr.lo ext/mbstring/libmbfl/nls/nls_neutral.lo ext/mbstring/libmbfl/nls/nls_ru.lo ext/mbstring/libmbfl/nls/nls_uni.lo ext/mbstring/libmbfl/nls/nls_zh.lo ext/mbstring/libmbfl/nls/nls_hy.lo ext/mbstring/libmbfl/nls/nls_tr.lo ext/mbstring/libmbfl/nls/nls_ua.lo ext/pcntl/pcntl.lo ext/pcntl/php_signal.lo ext/phar/util.lo ext/phar/tar.lo ext/phar/zip.lo ext/phar/stream.lo ext/phar/func_interceptors.lo ext/phar/dirstream.lo ext/phar/phar.lo ext/phar/phar_object.lo ext/phar/phar_path_check.lo ext/posix/posix.lo ext/reflection/php_reflection.lo ext/snappy/snappy.lo ext/spl/php_spl.lo ext/spl/spl_functions.lo ext/spl/spl_iterators.lo ext/spl/spl_array.lo ext/spl/spl_directory.lo ext/spl/spl_exceptions.lo ext/spl/spl_observer.lo ext/spl/spl_dllist.lo ext/spl/spl_heap.lo ext/spl/spl_fixedarray.lo ext/standard/crypt_freesec.lo ext/standard/crypt_blowfish.lo ext/standard/crypt_sha512.lo ext/standard/crypt_sha256.lo ext/standard/php_crypt_r.lo ext/standard/array.lo ext/standard/base64.lo ext/standard/basic_functions.lo ext/standard/browscap.lo ext/standard/crc32.lo ext/standard/crypt.lo ext/standard/datetime.lo ext/standard/dir.lo ext/standard/dl.lo ext/standard/dns.lo ext/standard/exec.lo ext/standard/file.lo ext/standard/filestat.lo ext/standard/flock_compat.lo ext/standard/formatted_print.lo ext/standard/fsock.lo ext/standard/head.lo ext/standard/html.lo ext/standard/image.lo ext/standard/info.lo ext/standard/iptc.lo ext/standard/lcg.lo ext/standard/link.lo ext/standard/mail.lo ext/standard/math.lo ext/standard/md5.lo ext/standard/metaphone.lo ext/standard/microtime.lo ext/standard/pack.lo ext/standard/pageinfo.lo ext/standard/quot_print.lo ext/standard/rand.lo ext/standard/mt_rand.lo ext/standard/soundex.lo ext/standard/string.lo ext/standard/scanf.lo ext/standard/syslog.lo ext/standard/type.lo ext/standard/uniqid.lo ext/standard/url.lo ext/standard/var.lo ext/standard/versioning.lo ext/standard/assert.lo ext/standard/strnatcmp.lo ext/standard/levenshtein.lo ext/standard/incomplete_class.lo ext/standard/url_scanner_ex.lo ext/standard/ftp_fopen_wrapper.lo ext/standard/http_fopen_wrapper.lo ext/standard/php_fopen_wrapper.lo ext/standard/credits.lo ext/standard/css.lo ext/standard/var_unserializer.lo ext/standard/ftok.lo ext/standard/sha1.lo ext/standard/user_filters.lo ext/standard/uuencode.lo ext/standard/filters.lo ext/standard/proc_open.lo ext/standard/streamsfuncs.lo ext/standard/http.lo ext/standard/password.lo ext/standard/random.lo ext/standard/net.lo ext/standard/hrtime.lo ext/standard/crc32_x86.lo ext/tokenizer/tokenizer.lo ext/tokenizer/tokenizer_data.lo ext/xmlreader/php_xmlreader.lo Zend/asm/make_x86_64_sysv_elf_gas.lo Zend/asm/jump_x86_64_sysv_elf_gas.lo TSRM/TSRM.lo main/main.lo main/snprintf.lo main/spprintf.lo main/fopen_wrappers.lo main/alloca.lo main/php_scandir.lo main/php_ini.lo main/SAPI.lo main/rfc1867.lo main/php_content_types.lo main/strlcpy.lo main/strlcat.lo main/explicit_bzero.lo main/reentrancy.lo main/php_variables.lo main/php_ticks.lo main/network.lo main/php_open_temporary_file.lo main/output.lo main/getopt.lo main/php_syslog.lo main/streams/streams.lo main/streams/cast.lo main/streams/memory.lo main/streams/filter.lo main/streams/plain_wrapper.lo main/streams/userspace.lo main/streams/transports.lo main/streams/xp_socket.lo main/streams/mmap.lo main/streams/glob_wrapper.lo Zend/zend_language_parser.lo Zend/zend_language_scanner.lo Zend/zend_ini_parser.lo Zend/zend_ini_scanner.lo Zend/zend_alloc.lo Zend/zend_compile.lo Zend/zend_constants.lo Zend/zend_dtrace.lo Zend/zend_execute_API.lo Zend/zend_highlight.lo Zend/zend_llist.lo Zend/zend_vm_opcodes.lo Zend/zend_opcode.lo Zend/zend_operators.lo Zend/zend_ptr_stack.lo Zend/zend_stack.lo Zend/zend_variables.lo Zend/zend.lo Zend/zend_API.lo Zend/zend_extensions.lo Zend/zend_hash.lo Zend/zend_list.lo Zend/zend_builtin_functions.lo Zend/zend_attributes.lo Zend/zend_execute.lo Zend/zend_ini.lo Zend/zend_sort.lo Zend/zend_multibyte.lo Zend/zend_stream.lo Zend/zend_iterators.lo Zend/zend_interfaces.lo Zend/zend_exceptions.lo Zend/zend_strtod.lo Zend/zend_gc.lo Zend/zend_closures.lo Zend/zend_weakrefs.lo Zend/zend_float.lo Zend/zend_string.lo Zend/zend_signal.lo Zend/zend_generators.lo Zend/zend_virtual_cwd.lo Zend/zend_ast.lo Zend/zend_objects.lo Zend/zend_object_handlers.lo Zend/zend_objects_API.lo Zend/zend_default_classes.lo Zend/zend_inheritance.lo Zend/zend_smart_str.lo Zend/zend_cpuinfo.lo Zend/zend_gdb.lo Zend/zend_observer.lo Zend/zend_system_id.lo Zend/zend_enum.lo Zend/zend_fibers.lo Zend/zend_max_execution_timer.lo Zend/Optimizer/zend_optimizer.lo Zend/Optimizer/pass1.lo Zend/Optimizer/pass3.lo Zend/Optimizer/optimize_func_calls.lo Zend/Optimizer/block_pass.lo Zend/Optimizer/optimize_temp_vars_5.lo Zend/Optimizer/nop_removal.lo Zend/Optimizer/compact_literals.lo Zend/Optimizer/zend_cfg.lo Zend/Optimizer/zend_dfg.lo Zend/Optimizer/dfa_pass.lo Zend/Optimizer/zend_ssa.lo Zend/Optimizer/zend_inference.lo Zend/Optimizer/zend_func_info.lo Zend/Optimizer/zend_call_graph.lo Zend/Optimizer/sccp.lo Zend/Optimizer/scdf.lo Zend/Optimizer/dce.lo Zend/Optimizer/escape_analysis.lo Zend/Optimizer/compact_vars.lo Zend/Optimizer/zend_dump.lo main/internal_functions_cli.lo sapi/micro/php_micro.lo sapi/micro/php_micro_helper.lo sapi/micro/php_micro_hooks.lo sapi/cli/php_cli_process_title.lo sapi/cli/ps_title.lo sapi/micro/php_micro_fileinfo.lo /home/runner/work/flow/flow/buildroot/lib/libsnappy.a /home/runner/work/flow/flow/buildroot/lib/libgmp.a /home/runner/work/flow/flow/buildroot/lib/libssl.a /home/runner/work/flow/flow/buildroot/lib/libcrypto.a /home/runner/work/flow/flow/buildroot/lib/libxml2.a /home/runner/work/flow/flow/buildroot/lib/libz.a /home/runner/work/flow/flow/buildroot/lib/libiconv.a /home/runner/work/flow/flow/buildroot/lib/libcharset.a /home/runner/work/flow/flow/buildroot/lib/libonig.a -lstdc++   -o sapi/micro/micro.sfx
[07:24:32] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[2]: cd '/home/runner/work/flow/flow/source/php-src' && make -j2 EXTRA_CFLAGS='-g -Os -fno-ident -Xcompiler -march=corei7 -Xcompiler -mtune=core-avx2' EXTRA_LIBS='/home/runner/work/flow/flow/buildroot/lib/libsnappy.a /home/runner/work/flow/flow/buildroot/lib/libgmp.a /home/runner/work/flow/flow/buildroot/lib/libssl.a /home/runner/work/flow/flow/buildroot/lib/libcrypto.a /home/runner/work/flow/flow/buildroot/lib/libxml2.a /home/runner/work/flow/flow/buildroot/lib/libz.a /home/runner/work/flow/flow/buildroot/lib/libiconv.a /home/runner/work/flow/flow/buildroot/lib/libcharset.a /home/runner/work/flow/flow/buildroot/lib/libonig.a -lstdc++ ' EXTRA_LDFLAGS_PROGRAM='  -all-static' micro at phar:///home/runner/work/flow/flow/spc/src/globals/functions.php(88)
[07:24:32] [ERRO] #0 phar:///home/runner/work/flow/flow/spc/src/SPC/util/UnixShell.php(44): f_passthru('cd '/home/runne...')
#1 phar:///home/runner/work/flow/flow/spc/src/SPC/builder/linux/LinuxBuilder.php(286): SPC\util\UnixShell->exec('cd '/home/runne...')
```

Refs: https://github.com/flow-php/flow/actions/runs/6245268400/job/16953595059

**Comment by crazywhalecc** [comment]
`snappy` is a C++ extension (library snappy is using cpp). Extensions using C++ cannot be compiled under Ubuntu and need to be compiled in Alpine Linux. The easist way is `bin/spc-alpine-docker`.
