### ISSUE TITLE
Freetype doesn't compile

### ISSUE THREAD

**Issue by dunglas** [crazywhalecc/static-php-cli#269]
https://github.com/dunglas/frankenphp/actions/runs/6881409688/job/18717691144?pr=304

Adding `--debug` doesn't give more informations

**Comment by crazywhalecc** [comment]
https://github.com/crazywhalecc/static-php-cli/commit/e3671387fc3b2f09c11ba800e7b11236a3e46a53

It seems to be related to the fact that I changed the invalid freetype address yesterday. The tag source code of the GitHub mirror repository seems to be different from the source code of gnu.org.

**Comment by dunglas** [comment]
Better logs:

```
#18 26.54 [10:06:05] [INFO] Building required library [freetype]
#18 26.54 [10:06:05] [INFO] Entering dir: /static-php-cli/source/freetype
#18 26.54 [10:06:05] [INFO] [EXEC] ./configure --enable-static --disable-shared --without-harfbuzz --prefix= --with-png --with-bzip2=/static-php-cli/buildroot --without-brotli 
#18 26.54 [10:06:05] [DEBU] Running command with direct output: cd '/static-php-cli/source/freetype' && ./configure --enable-static --disable-shared --without-harfbuzz --prefix= --with-png --with-bzip2=/static-php-cli/buildroot --without-brotli 
#18 26.56 
#18 26.56 FreeType build system -- automatic system detection
#18 26.56 
#18 26.56 The following settings are used:
#18 26.56 
#18 26.56   platform                    unix
#18 26.56   compiler                    gcc
#18 26.56   configuration directory     ./builds/unix
#18 26.56   configuration rules         ./builds/unix/unix.mk
#18 26.56 
#18 26.56 If this does not correspond to your system or settings please remove the file
#18 26.56 `config.mk' from this directory then read the INSTALL file for help.
#18 26.56 
#18 26.56 Otherwise, simply type `make' again to build the library,
#18 26.56 or `make refdoc' to build the API reference (this needs Python >= 3.5).
#18 26.56 
#18 26.56 Checking out submodule in `subprojects/dlg'
#18 26.56 git --git-dir=. submodule init
#18 26.57 fatal: not a git repository: '.'
#18 26.57 make: *** [builds/toplevel.mk:173: check_out_submodule] Error 128
#18 26.57 [10:06:05] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[2]: cd '/static-php-cli/source/freetype' && ./configure --enable-static --disable-shared --without-harfbuzz --prefix= --with-png --with-bzip2=/static-php-cli/buildroot --without-brotli  at /static-php-cli/src/globals/functions.php(89)
#18 26.57 [10:06:05] [ERRO] #0 /static-php-cli/src/SPC/util/UnixShell.php(44): f_passthru()
#18 26.57 #1 /static-php-cli/src/SPC/builder/unix/library/freetype.php(29): SPC\util\UnixShell->exec()
#18 26.57 #2 /static-php-cli/src/SPC/builder/LibraryBase.php(143): SPC\builder\linux\library\freetype->build()
#18 26.57 #3 /static-php-cli/src/SPC/builder/LibraryBase.php(150): SPC\builder\LibraryBase->tryBuild()
#18 26.57 #4 /static-php-cli/src/SPC/builder/BuilderBase.php(88): SPC\builder\LibraryBase->tryBuild()
#18 26.57 #5 /static-php-cli/src/SPC/command/BuildCliCommand.php(80): SPC\builder\BuilderBase->buildLibs()
#18 26.57 #6 /static-php-cli/src/SPC/command/BaseCommand.php(83): SPC\command\BuildCliCommand->handle()
#18 26.57 #7 /static-php-cli/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute()
#18 26.57 #8 /static-php-cli/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run()
#18 26.57 #9 /static-php-cli/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#18 26.57 #10 /static-php-cli/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#18 26.57 #11 /static-php-cli/bin/spc(15): Symfony\Component\Console\Application->run()
#18 26.57 #12 {main}
#18 ERROR: process "/bin/sh -c ./bin/spc build --debug --build-embed --enable-zts --disable-opcache-jit \"$PHP_EXTENSIONS\" --with-libs=\"$PHP_EXTENSION_LIBS\"" did not complete successfully: exit code: 1
------
 > [stage-0  6/17] RUN ./bin/spc build --debug --build-embed --enable-zts --disable-opcache-jit "apcu,bcmath,bz2,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,gd,iconv,intl,ldap,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sqlite3,sysvsem,tokenizer,xml,xmlreader,xmlwriter,zip,zlib" --with-libs="freetype,libjpeg,libavif,libwebp,libzip,bzip2":
26.57 #3 /static-php-cli/src/SPC/builder/LibraryBase.php(150): SPC\builder\LibraryBase->tryBuild()
26.57 #4 /static-php-cli/src/SPC/builder/BuilderBase.php(88): SPC\builder\LibraryBase->tryBuild()
26.57 #5 /static-php-cli/src/SPC/command/BuildCliCommand.php(80): SPC\builder\BuilderBase->buildLibs()
26.57 #6 /static-php-cli/src/SPC/command/BaseCommand.php(83): SPC\command\BuildCliCommand->handle()
26.57 #7 /static-php-cli/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute()
26.57 #8 /static-php-cli/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run()
26.57 #9 /static-php-cli/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
26.57 #10 /static-php-cli/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
26.57 #11 /static-php-cli/bin/spc(15): Symfony\Component\Console\Application->run()
26.57 #12 {main}
```
