### ISSUE TITLE
spc build

### ISSUE THREAD

**Issue by KingBes** [crazywhalecc/static-php-cli#340]
```shell
spc build "mysqlnd,pdo_mysql" --build-micro --debug
     _        _   _                 _
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.1.0-beta.2
                             |_|         |_|
[15:01:48] [WARN] PHP Warning: Trying to access array offset on false in D:\project\php\static-php-cli\src\SPC\builder\windows\WindowsBuilder.php on 38
[15:01:48] [DEBU] Running command (no output) : echo %NUMBER_OF_PROCESSORS%
[15:01:48] [INFO] Build OS:       Windows (AMD64)
[15:01:48] [INFO] Build SAPI:     micro
[15:01:48] [INFO] Extensions (3): mysqlnd, pdo, pdo_mysql
[15:01:48] [INFO] Libraries (1):  zlib
[15:01:48] [INFO] Strip Binaries: yes
[15:01:48] [INFO] Enable ZTS:     no
[15:01:48] [INFO] PHP Version:    8.2.16
[15:01:48] [INFO] Extra Exts (1): pdo
[15:01:48] [NOTI] Build will start after 2s ...
[15:01:50] [DEBU] scanning directory D:\project\php\static-php-cli\src\SPC\builder\windows\library
[15:01:50] [DEBU] Source [zlib] already extracted in D:\project\php\static-php-cli\source/zlib, skip !
[15:01:50] [INFO] Building required library [zlib]
[15:01:50] [DEBU] Removing path recursively: "D:\project\php\static-php-cli\source\zlib\build"
[15:01:50] [DEBU] scanning directory D:\project\php\static-php-cli\source\zlib\build
[15:01:50] [DEBU] Making new directory recursive: D:\project\php\static-php-cli\source/zlib\build
[15:01:50] [INFO] Entering dir: D:\project\php\static-php-cli\source/zlib
[15:01:50] [INFO] [EXEC] D:\project\php\static-php-cli\php-sdk-binary-tools\phpsdk--x64.bat -t D:\project\php\static-php-cli\source\590894066_wrapper.bat --task-args "-B build -A x64 -DCMAKE_TOOLCHAIN_FILE=D:\project\php\static-php-cli\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=D:\project\php\static-php-cli\buildroot "
cd /d "D:\project\php\static-php-cli\source/zlib" && D:\project\php\static-php-cli\php-sdk-binary-tools\phpsdk--x64.bat -t D:\project\php\static-php-cli\source\590894066_wrapper.bat --task-args "-B build -A x64 -DCMAKE_TOOLCHAIN_FILE=D:\project\php\static-php-cli\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=D:\project\php\static-php-cli\buildroot "
[15:01:50] [DEBU] Running command with direct output: cd /d "D:\project\php\static-php-cli\source/zlib" && D:\project\php\static-php-cli\php-sdk-binary-tools\phpsdk--x64.bat -t D:\project\php\static-php-cli\source\590894066_wrapper.bat --task-args "-B build -A x64 -DCMAKE_TOOLCHAIN_FILE=D:\project\php\static-php-cli\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=D:\project\php\static-php-cli\buildroot "
'D:\project\php\static-php-cli\php-sdk-binary-tools\phpsdk--x64.bat' is not recognized as an internal or external command,
operable program or batch file.

   SPC\exception\RuntimeException

  Command run failed with code[1]: cd /d "D:\project\php\static-php-cli\source/zlib" && D:\project\php\static-php-cli\php-sdk-binary-tools\phpsdk--x64.bat -t D:\project\php\static-php-cli\source\590894066_wrapper.bat --task-args "-B build -A x64 -DCMAKE_TOOLCHAIN_FILE=D:\project\php\static-php-cli\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=D:\project\php\static-php-cli\buildroot "

  at src\globals\functions.php:93
     89▕         logger()->debug('Running command with direct output: ' . $cmd);
     90▕     }
     91▕     $ret = passthru($cmd, $code);
     92▕     if ($code !== 0) {
  ➜  93▕         throw new RuntimeException('Command run failed with code[' . $code . ']: ' . $cmd, $code);
     94▕     }
     95▕     return $ret;
     96▕ }
     97▕

  1   src\SPC\util\WindowsCmd.php:49

  2   src\SPC\util\WindowsCmd.php:55
      SPC\util\WindowsCmd::exec("cd /d "D:\project\php\static-php-cli\source/zlib" && D:\project\php\static-php-cli\php-sdk-binary-tools\phpsdk--x64.bat -t D:\project\php\static-php-cli\source\590894066_wrapper.bat --task-args "-B build -A x64 -DCMAKE_TOOLCHAIN_FILE=D:\project\php\static-php-cli\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=D:\project\php\static-php-cli\buildroot "")

[15:01:50] [CRIT] You can report this exception to static-php-cli GitHub repo.

```

**Comment by crazywhalecc** [comment]
You may need to install Visual Studio 2019/2022 and run `spc doctor` first to prepare environment.

**Comment by KingBes** [comment]
> 可能需要安装 Visual Studio 2019/2022 并先运行以准备环境。请参见：https://static-php.dev/en/guide/build-on-windows.html`spc doctor`

```shell
PS C:\project\php\spc> ./spc.exe doctor
     _        _   _                 _
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.1.0-beta.3
                             |_|         |_|
Checking if current OS are supported ... Windows AMD64, supported (but not tested on this distro)
Checking if Visual Studio are installed ... Visual Studio not installed, please install VS 2022/2019.
Some check items can not be fixed !
PS C:\project\php\spc> cl
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.39.33519 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]
```

**Comment by KingBes** [comment]
> 可能需要安装 Visual Studio 2019/2022 并先运行以准备环境。请参见：https://static-php.dev/en/guide/build-on-windows.html`spc doctor`

```shell
PS C:\project\php\spc> ./spc.exe doctor
     _        _   _                 _
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.1.0-beta.3
                             |_|         |_|
Checking if current OS are supported ... Windows AMD64, supported (but not tested on this distro)
Checking if Visual Studio are installed ... Visual Studio not installed, please install VS 2022/2019.
Some check items can not be fixed !
PS C:\project\php\spc> cl
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.39.33519 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]
```

**Comment by crazywhalecc** [comment]
<img width="986" alt="image" src="https://github.com/crazywhalecc/static-php-cli/assets/20330940/4c3eea89-d67d-4dd4-99fd-1e8c064e9be9">

确认下是不是我漏了 Visual Studio 安装路径导致的原因？因为我只找了这么几个路径。

**Comment by KingBes** [comment]
> <img alt="image" width="986" src="https://private-user-images.githubusercontent.com/20330940/305608660-4c3eea89-d67d-4dd4-99fd-1e8c064e9be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjQxMDEsIm5iZiI6MTcwODE2MzgwMSwicGF0aCI6Ii8yMDMzMDk0MC8zMDU2MDg2NjAtNGMzZWVhODktZDY3ZC00ZGQ0LTk5ZmQtMWU4YzA2NGU5YmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA5NTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMTQ3YmNlMTA5ODUzYTNjYjU2MDEzNzRkNjY1N2MyYWZhMDZmZDNmNGVlNTQ5MWEwY2ZhZjc2ZWFlNzdhNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ZufBkN034B1T7c9VI1is3HJxBH048CUT9UloGVaBJQ">
> 确认下是不是我漏了 Visual Studio 安装路径导致的原因？因为我只找了这么几个路径。

```shell
PS C:\project\php\spc> ./spc.exe build "openssl" --build-micro --debug
     _        _   _                 _
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.1.0-beta.3
                             |_|         |_|
[09:55:08] [DEBU] Running command (no output) : echo %NUMBER_OF_PROCESSORS%
[09:55:08] [INFO] Build OS:       Windows (AMD64)
[09:55:08] [INFO] Build SAPI:     micro
[09:55:08] [INFO] Extensions (2): zlib, openssl
[09:55:08] [INFO] Libraries (2):  zlib, openssl
[09:55:08] [INFO] Strip Binaries: yes
[09:55:08] [INFO] Enable ZTS:     no
[09:55:08] [INFO] PHP Version:    8.2.16
[09:55:08] [INFO] Extra Exts (1): zlib
[09:55:08] [NOTI] Build will start after 2s ...
[09:55:10] [DEBU] scanning directory phar://C:/project/php/spc/spc.exe\src\SPC\builder\windows\library
[09:55:10] [DEBU] Source [zlib] already extracted in C:\project\php\spc\source/zlib, skip !
[09:55:10] [DEBU] Source [openssl] already extracted in C:\project\php\spc\source/openssl, skip !
[09:55:10] [INFO] Building required library [zlib]
[09:55:10] [DEBU] Removing path recursively: "C:\project\php\spc\source\zlib\build"
[09:55:10] [DEBU] scanning directory C:\project\php\spc\source\zlib\build
[09:55:10] [DEBU] Making new directory recursive: C:\project\php\spc\source/zlib\build
[09:55:10] [INFO] Entering dir: C:\project\php\spc\source/zlib
[09:55:10] [INFO] [EXEC] C:\project\php\spc\php-sdk-binary-tools\phpsdk-vs17-x64.bat -t C:\project\php\spc\source\590894066_wrapper.bat --task-args "-B build -A x64 -DCMAKE_TOOLCHAIN_FILE=C:\project\php\spc\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=C:\project\php\spc\buildroot "
cd /d "C:\project\php\spc\source/zlib" && C:\project\php\spc\php-sdk-binary-tools\phpsdk-vs17-x64.bat -t C:\project\php\spc\source\590894066_wrapper.bat --task-args "-B build -A x64 -DCMAKE_TOOLCHAIN_FILE=C:\project\php\spc\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=C:\project\php\spc\buildroot "
[09:55:10] [DEBU] Running command with direct output: cd /d "C:\project\php\spc\source/zlib" && C:\project\php\spc\php-sdk-binary-tools\phpsdk-vs17-x64.bat -t C:\project\php\spc\source\590894066_wrapper.bat --task-args "-B build -A x64 -DCMAKE_TOOLCHAIN_FILE=C:\project\php\spc\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=C:\project\php\spc\buildroot "
[vcvarsall.bat] Environment initialized for: 'x64'

C:\project\php\spc\source\zlib>cmake -B build -A x64 -DCMAKE_TOOLCHAIN_FILE=C:\project\php\spc\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=C:\project\php\spc\buildroot
CMake Error: The source directory "C:/project/php/spc/source/zlib" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
[09:55:15] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[1]: cd /d "C:\project\php\spc\source/zlib" && C:\project\php\spc\php-sdk-binary-tools\phpsdk-vs17-x64.bat -t C:\project\php\spc\source\590894066_wrapper.bat --task-args "-B build -A x64 -DCMAKE_TOOLCHAIN_FILE=C:\project\php\spc\source\toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSKIP_INSTALL_FILES=ON -DCMAKE_INSTALL_PREFIX=C:\project\php\spc\buildroot " at phar://C:/project/php/spc/spc.exe/src/globals/functions.php(93)
[09:55:15] [ERRO] #0 phar://C:/project/php/spc/spc.exe/src/SPC/util/WindowsCmd.php(49): f_passthru('cd /d "C:\\proje...')
#1 phar://C:/project/php/spc/spc.exe/src/SPC/util/WindowsCmd.php(55): SPC\util\WindowsCmd->exec('cd /d "C:\\proje...')
#2 phar://C:/project/php/spc/spc.exe/src/SPC/builder/windows/library/zlib.php(20): SPC\util\WindowsCmd->execWithWrapper('C:\\project\\php\\...', '-B build -A x64...')
#3 phar://C:/project/php/spc/spc.exe/src/SPC/builder/LibraryBase.php(144): SPC\builder\windows\library\zlib->build()
#4 phar://C:/project/php/spc/spc.exe/src/SPC/builder/LibraryBase.php(152): SPC\builder\LibraryBase->tryBuild(true)
#5 phar://C:/project/php/spc/spc.exe/src/SPC/builder/windows/WindowsBuilder.php(218): SPC\builder\LibraryBase->tryBuild(false)
#6 phar://C:/project/php/spc/spc.exe/src/SPC/command/BuildCliCommand.php(104): SPC\builder\windows\WindowsBuilder->buildLibs(Array)
#7 phar://C:/project/php/spc/spc.exe/src/SPC/command/BaseCommand.php(96): SPC\command\BuildCliCommand->handle()
#8 phar://C:/project/php/spc/spc.exe/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar://C:/project/php/spc/spc.exe/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar://C:/project/php/spc/spc.exe/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(SPC\command\BuildCliCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar://C:/project/php/spc/spc.exe/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar://C:/project/php/spc/spc.exe/bin/spc(20): Symfony\Component\Console\Application->run()
#13 C:\project\php\spc\spc.exe(8): require('phar://C:/proje...')
#14 {main}
```

**Comment by crazywhalecc** [comment]
删除 source 目录，重新试一下？这个错误应该是 source 路径下的源码解压得不太对。
