### ISSUE TITLE
libuuid fails to build on linux

### ISSUE THREAD

**Issue by withinboredom** [crazywhalecc/static-php-cli#408]
This is the output:

```
[20:54:18] [DEBU] Running command with direct output: cd '/home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/source/libuuid' && make clean
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/source/libuuid/missing aclocal 
 cd . && /bin/bash /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/source/libuuid/missing automake --foreign
configure.ac:8: error: required file './compile' not found
configure.ac:8:   'automake --add-missing' can install 'compile'
make: *** [Makefile:395: Makefile.in] Error 1
[20:54:19] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[2]: cd '/home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/source/libuuid' && make clean at /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/src/globals/functions.php(100)
[20:54:19] [ERRO] #0 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/src/SPC/util/UnixShell.php(47): f_passthru()
#1 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/src/SPC/builder/unix/library/libuuid.php(33): SPC\util\UnixShell->exec()
#2 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/src/SPC/builder/LibraryBase.php(144): SPC\builder\linux\library\libuuid->build()
#3 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/src/SPC/builder/LibraryBase.php(152): SPC\builder\LibraryBase->tryBuild()
#4 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/src/SPC/builder/unix/UnixBuilderBase.php(143): SPC\builder\LibraryBase->tryBuild()
#5 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/src/SPC/command/BuildCliCommand.php(143): SPC\builder\unix\UnixBuilderBase->buildLibs()
#6 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/src/SPC/command/BaseCommand.php(99): SPC\command\BuildCliCommand->handle()
#7 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute()
#8 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#9 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#10 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#11 /home/runner/work/durable-php/durable-php/cli/dist/static-php-cli/bin/spc(21): Symfony\Component\Console\Application->run()
```

**Comment by crazywhalecc** [comment]
Fixed by #411 .
