### ISSUE TITLE
libtiff build fails on macOS

### ISSUE THREAD

**Issue by dunglas** [crazywhalecc/static-php-cli#480]
This is probably an upstream problem:

```
[12:52:20] [DEBU] Running command with direct output: cd '/Users/dunglas/workspace/frankenphp/dist/static-php-cli/source/libtiff' && make clean
Making clean in port
rm -rf .libs _libs
test -z "libport.la" || rm -f libport.la
rm -f ./so_locations
rm -f *.o
rm -f *.lo
Making clean in libtiff
test -z "libtiff.la " || rm -f libtiff.la 
rm -f ./so_locations
rm -rf .libs _libs
 rm -f mkg3states
rm -f *.o
rm -f *.lo
Making clean in tools
 rm -f tiffcp tiffdump tiffinfo tiffset tiffsplit
rm -rf .libs _libs
rm -f *.o
rm -f *.lo
Making clean in build
rm -rf .libs _libs
rm -f *.lo
Making clean in contrib
Making clean in addtiffo
rm -rf .libs _libs
 rm -f addtiffo
rm -f *.o
rm -f *.lo
Making clean in dbs
Making clean in xtiff
rm -rf .libs _libs
rm -f *.lo
rm -rf .libs _libs
 rm -f tiff-bi tiff-grayscale tiff-palette tiff-rgb
rm -f *.o
rm -f *.lo
Making clean in iptcutil
rm -rf .libs _libs
 rm -f iptcutil
rm -f *.o
rm -f *.lo
Making clean in mfs
rm -rf .libs _libs
rm -f *.lo
Making clean in pds
rm -rf .libs _libs
rm -f *.lo
Making clean in ras
rm -rf .libs _libs
rm -f *.lo
Making clean in stream
rm -rf .libs _libs
rm -f *.lo
Making clean in tags
rm -rf .libs _libs
rm -f *.lo
Making clean in win_dib
rm -rf .libs _libs
rm -f *.lo
rm -rf .libs _libs
rm -f *.lo
Making clean in test
 rm -f ascii_tag long_tag short_tag strip_rw rewrite custom_dir custom_dir_EXIF_231 defer_strile_loading defer_strile_writing test_directory test_open_options test_append_to_strip test_ifd_loop_detection testtypes test_signed_tags rational_precision2double test_write_read_tags test_transferfunction_write_read
test -z "test_packbits.tif o-*" || rm -f test_packbits.tif o-*
rm -rf .libs _libs
rm -f *.o
test -z "ascii_tag.log long_tag.log short_tag.log strip_rw.log rewrite.log custom_dir.log custom_dir_EXIF_231.log defer_strile_loading.log defer_strile_writing.log test_directory.log test_open_options.log test_append_to_strip.log test_ifd_loop_detection.log testtypes.log test_signed_tags.log rational_precision2double.log test_write_read_tags.log test_transferfunction_write_read.log tiffcp-g3.sh.log tiffcp-g3-1d.sh.log tiffcp-g3-1d-fill.sh.log tiffcp-g3-2d.sh.log tiffcp-g3-2d-fill.sh.log tiffcp-g4.sh.log tiffcp-logluv.sh.log tiffcp-lzw-compat.sh.log tiffcp-lzw-scanline-decode.sh.log tiffdump.sh.log tiffinfo.sh.log tiffcp-split.sh.log tiffcp-split-join.sh.log" || rm -f ascii_tag.log long_tag.log short_tag.log strip_rw.log rewrite.log custom_dir.log custom_dir_EXIF_231.log defer_strile_loading.log defer_strile_writing.log test_directory.log test_open_options.log test_append_to_strip.log test_ifd_loop_detection.log testtypes.log test_signed_tags.log rational_precision2double.log test_write_read_tags.log test_transferfunction_write_read.log tiffcp-g3.sh.log tiffcp-g3-1d.sh.log tiffcp-g3-1d-fill.sh.log tiffcp-g3-2d.sh.log tiffcp-g3-2d-fill.sh.log tiffcp-g4.sh.log tiffcp-logluv.sh.log tiffcp-lzw-compat.sh.log tiffcp-lzw-scanline-decode.sh.log tiffdump.sh.log tiffinfo.sh.log tiffcp-split.sh.log tiffcp-split-join.sh.log
test -z "ascii_tag.trs long_tag.trs short_tag.trs strip_rw.trs rewrite.trs custom_dir.trs custom_dir_EXIF_231.trs defer_strile_loading.trs defer_strile_writing.trs test_directory.trs test_open_options.trs test_append_to_strip.trs test_ifd_loop_detection.trs testtypes.trs test_signed_tags.trs rational_precision2double.trs test_write_read_tags.trs test_transferfunction_write_read.trs tiffcp-g3.sh.trs tiffcp-g3-1d.sh.trs tiffcp-g3-1d-fill.sh.trs tiffcp-g3-2d.sh.trs tiffcp-g3-2d-fill.sh.trs tiffcp-g4.sh.trs tiffcp-logluv.sh.trs tiffcp-lzw-compat.sh.trs tiffcp-lzw-scanline-decode.sh.trs tiffdump.sh.trs tiffinfo.sh.trs tiffcp-split.sh.trs tiffcp-split-join.sh.trs" || rm -f ascii_tag.trs long_tag.trs short_tag.trs strip_rw.trs rewrite.trs custom_dir.trs custom_dir_EXIF_231.trs defer_strile_loading.trs defer_strile_writing.trs test_directory.trs test_open_options.trs test_append_to_strip.trs test_ifd_loop_detection.trs testtypes.trs test_signed_tags.trs rational_precision2double.trs test_write_read_tags.trs test_transferfunction_write_read.trs tiffcp-g3.sh.trs tiffcp-g3-1d.sh.trs tiffcp-g3-1d-fill.sh.trs tiffcp-g3-2d.sh.trs tiffcp-g3-2d-fill.sh.trs tiffcp-g4.sh.trs tiffcp-logluv.sh.trs tiffcp-lzw-compat.sh.trs tiffcp-lzw-scanline-decode.sh.trs tiffdump.sh.trs tiffinfo.sh.trs tiffcp-split.sh.trs tiffcp-split-join.sh.trs
test -z "test-suite.log" || rm -f test-suite.log
rm -f *.lo
Making clean in doc
rm -rf .libs _libs
rm -r html
rm: html: No such file or directory
make[1]: *** [clean-local] Error 1
make: *** [clean-recursive] Error 1
[12:52:20] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[2]: cd '/Users/dunglas/workspace/frankenphp/dist/static-php-cli/source/libtiff' && make clean at /Users/dunglas/workspace/frankenphp/dist/static-php-cli/src/globals/functions.php(147)
[12:52:20] [ERRO] #0 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/src/SPC/util/UnixShell.php(50): f_passthru('cd '/Users/dung...')
#1 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/src/SPC/builder/unix/library/libtiff.php(25): SPC\util\UnixShell->exec('cd '/Users/dung...')
#2 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/src/SPC/builder/LibraryBase.php(144): SPC\builder\macos\library\libtiff->build()
#3 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/src/SPC/builder/LibraryBase.php(152): SPC\builder\LibraryBase->tryBuild(true)
#4 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/src/SPC/builder/BuilderBase.php(58): SPC\builder\LibraryBase->tryBuild(false)
#5 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/src/SPC/command/BuildCliCommand.php(151): SPC\builder\BuilderBase->buildLibs()
#6 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/src/SPC/command/BaseCommand.php(101): SPC\command\BuildCliCommand->handle()
#7 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(SPC\command\BuildCliCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/dunglas/workspace/frankenphp/dist/static-php-cli/bin/spc(21): Symfony\Component\Console\Application->run()
#12 {main}
```

**Comment by dunglas** [comment]
Caused (and fixed) by https://gitlab.com/libtiff/libtiff/-/merge_requests/635.
