### ISSUE TITLE
libyaml build fails

### ISSUE THREAD

**Issue by dunglas** [crazywhalecc/static-php-cli#498]
Error:

```
#28 1257.6 [13:28:39] [INFO] Building required library [libyaml]
#28 1257.6 [13:28:39] [DEBU] Making new directory recursive: /go/src/app/dist/static-php-cli/source/libyaml/build
#28 1257.6 [13:28:39] [INFO] Entering dir: /go/src/app/dist/static-php-cli/source/libyaml/build
#28 1257.6 [13:28:39] [INFO] [EXEC] cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_INSTALL_LIBDIR=/lib -DCMAKE_INSTALL_INCLUDEDIR=/include -DCMAKE_TOOLCHAIN_FILE=/go/src/app/dist/static-php-cli/source/toolchain.cmake ..
#28 1257.6 [13:28:39] [DEBU] Running command with direct output: cd '/go/src/app/dist/static-php-cli/source/libyaml/build' && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_INSTALL_LIBDIR=/lib -DCMAKE_INSTALL_INCLUDEDIR=/include -DCMAKE_TOOLCHAIN_FILE=/go/src/app/dist/static-php-cli/source/toolchain.cmake ..
#28 1257.6 -- The C compiler identification is GNU 13.2.1
#28 1257.6 -- Detecting C compiler ABI info
#28 1257.6 -- Detecting C compiler ABI info - done
#28 1257.6 -- Check for working C compiler: /usr/bin/gcc - skipped
#28 1257.6 -- Detecting C compile features
#28 1257.6 -- Detecting C compile features - done
#28 1257.6 -- Configuring incomplete, errors occurred!
#28 1257.6 [13:28:39] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[1]: cd '/go/src/app/dist/static-php-cli/source/libyaml/build' && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_INSTALL_LIBDIR=/lib -DCMAKE_INSTALL_INCLUDEDIR=/include -DCMAKE_TOOLCHAIN_FILE=/go/src/app/dist/static-php-cli/source/toolchain.cmake .. at /go/src/app/dist/static-php-cli/src/globals/functions.php(147)
#28 1257.6 [13:28:39] [ERRO] #0 /go/src/app/dist/static-php-cli/src/SPC/util/UnixShell.php(50): f_passthru()
#28 1257.6 #1 /go/src/app/dist/static-php-cli/src/SPC/builder/unix/library/libyaml.php(38): SPC\util\UnixShell->exec()
#28 1257.6 #2 /go/src/app/dist/static-php-cli/src/SPC/builder/LibraryBase.php(153): SPC\builder\linux\library\libyaml->build()
#28 1257.6 #3 /go/src/app/dist/static-php-cli/src/SPC/builder/LibraryBase.php(161): SPC\builder\LibraryBase->tryBuild()
#28 1257.6 #4 /go/src/app/dist/static-php-cli/src/SPC/builder/BuilderBase.php(58): SPC\builder\LibraryBase->tryBuild()
#28 1257.6 #5 /go/src/app/dist/static-php-cli/src/SPC/command/BuildCliCommand.php(151): SPC\builder\BuilderBase->buildLibs()
#28 1257.6 #6 /go/src/app/dist/static-php-cli/src/SPC/command/BaseCommand.php(101): SPC\command\BuildCliCommand->handle()
#28 1257.6 #7 /go/src/app/dist/static-php-cli/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute()
#28 1257.6 #8 /go/src/app/dist/static-php-cli/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#28 1257.6 #9 /go/src/app/dist/static-php-cli/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#28 1257.6 #10 /go/src/app/dist/static-php-cli/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#28 1257.6 #11 /go/src/app/dist/static-php-cli/bin/spc(21): Symfony\Component\Console\Application->run()
#28 1257.6 #12 {main}
#28 ERROR: process "/bin/ash -eo pipefail -c GITHUB_TOKEN=$(cat /run/secrets/github-token) ./build-static.sh && \trm -Rf dist/static-php-cli/source/*" did not complete successfully: exit code: 1
------
```

**Comment by crazywhalecc** [comment]
Will be fixed in #499 . Wrong slashes for patching.
